import "server-only";
import { prisma } from "../db";

/** Statements are generated by a scheduled job once real transaction
 * history exists (out of scope for this build — see
 * docs/production/11-implementation-phases.md). This reads whatever real
 * rows exist; it never fabricates a statement. */
export async function listStatementsForCustomer(customerProfileId: string) {
  return prisma.statement.findMany({
    where: { account: { customerProfileId } },
    include: { account: true },
    orderBy: { periodStart: "desc" },
  });
}
